/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-07-24 11:13:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.UserDTO;
import Model.UserDTO;
import Model.UserDTO;

public final class Explain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./header.jsp", Long.valueOf(1721456487285L));
    _jspx_dependants.put("/./footer.jsp", Long.valueOf(1721487489457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Model.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>제품 설명</title>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("@font-face {\n");
      out.write("    font-family: 'GangwonEdu_OTFBoldA';\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/GangwonEdu_OTFBoldA.woff') format('woff');\n");
      out.write("    font-weight: normal;\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"is-preload\" style=\"font-family: 'GangwonEdu_OTFBoldA';\">\n");
      out.write("\n");
      out.write("	<div id=\"page-wrapper\">\n");
      out.write("\n");
      out.write("		<!-- Header -->\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		UserDTO udto = (UserDTO)session.getAttribute("udto");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("		<header id=\"header\">\r\n");
      out.write("			<h1 style=\"color:white;font-size:xx-large;top:10px;\">\r\n");
      out.write("				<a href=\"Index.jsp\" style=\"color:white;font-size:50px;\">VisioMed&nbsp;&nbsp;</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			<nav id=\"nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"Index.jsp\">홈</a></li>\r\n");
      out.write("					<li><a href=\"select_handi.jsp\">정보 등록 및 조회&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='icon solid fa fa-angle-down'></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"reg_handi.jsp\">회원 정보 등록</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"#\">커뮤니티&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='fa fa-angle-down'></i></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"qnaMain.jsp\">문의하기</a></li>\r\n");
      out.write("							<li><a href=\"storyMain.jsp\">정보 공유</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"Mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("\r\n");
      out.write("					");
 if(udto != null){ 
      out.write("\r\n");
      out.write("						<li><a href=\"LogoutServiceCon.do\" class=\"button\" style=\"color: black;\">로그아웃</a></li>\r\n");
      out.write("					");
} else{
      out.write("\r\n");
      out.write("						<li><a href=\"Login.jsp\" class=\"button\" >로그인</a></li>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("		\n");
      out.write("		\n");
      out.write("\n");
      out.write("		<!-- Main -->\n");
      out.write("		<section id=\"main\" class=\"container\">\n");
      out.write("			<header>\n");
      out.write("				<h2>VisioMed</h2>\n");
      out.write("				<p>음성 API를 활용한 스마트 약 보관함</p>\n");
      out.write("			</header>\n");
      out.write("			\n");
      out.write("			<div class=\"box\">\n");
      out.write("				\n");
      out.write("				<i class=\"fa-solid fa-door-open fa-2x\"></i>\n");
      out.write("				<h3>제품 소개</h3>\n");
      out.write("				<p>약 이름을 제대로 확인하지 못하여 잘못된 사용을 할 수 있는 시각장애인, 시력이 악화되어 생활이 불편한\n");
      out.write("					고객님들을 위한 음성으로 약 이름과 정보를 알려주는 스마트 약 보관함</p>\n");
      out.write("				<div class=\"row\">\n");
      out.write("					<div class=\"row-6 row-12-mobilep\">\n");
      out.write("						<i class=\"fa-solid fa-door-open fa-2x\"></i>\n");
      out.write("						<h3>이용 방법</h3>\n");
      out.write("						\n");
      out.write("						\n");
      out.write("						<h4><i class=\"fa-solid fa-window-maximize\"></i>&nbsp;&nbsp;웹 사이트</h4>\n");
      out.write("						<p>\n");
      out.write("							1.회원 가입<br> - 복지사 또는 보호자를 선택하고 양식에 맞게 입력 후 가입해주세요.\n");
      out.write("						</p>\n");
      out.write("						<p>\n");
      out.write("							2. 정보 등록 및 조회<br> - 실사용자의 정보를 등록하고 복용하거나 사용하는 약 정보를 등록해주세요<br>\n");
      out.write("							- 약 정보를 등록할 때, 해당 페이지 상단의 제품 사진을 참고하여 입력해주세요.\n");
      out.write("						</p>\n");
      out.write("						<p>\n");
      out.write("							3. 마이페이지<br> - 비밀번호 변경을 통하여 비밀번호 변경을 할 수 있습니다. - 복지사일 경우\n");
      out.write("							관리하는 보호자 일부 정보를 확인 할 수 있습니다. - 보호자일 경우 담당하는 복지사 일부 정보를 확인 할 수\n");
      out.write("							있습니다.\n");
      out.write("						</p>\n");
      out.write("					</div>\n");
      out.write("					\n");
      out.write("					<div class=\"row-6 row-12-mobilep\">\n");
      out.write("						<h4><i class=\"fa-solid fa-prescription-bottle-medical\"></i></i>&nbsp;&nbsp;약 보관함</h4>\n");
      out.write("						<p>\n");
      out.write("							1. 쉽게 약 위치를 찾을 수 있는 곳에 제품을 설치해주세요.<br> 2. WI-FI와 VisioMed를\n");
      out.write("							연결해주세요.<br> 3. 보관함 앞에 버튼을 누르면 웹페이지에 등록한 약 정보를 음성으로 알려줍니다.<br>\n");
      out.write("						</p>\n");
      out.write("\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!-- Footer -->\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer id=\"footer\" style=\"padding:3em 0 3em 0;\">\r\n");
      out.write("  		<div class=\"inner\">\r\n");
      out.write("  		<a href=\"#\" class=\"page-top\" style=\"position: relative;left:350px;\">위로가기</a>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">전화: (+82)010-2512-5397</p>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">주소: 서울시, 성북구, 성북로 176</p>\r\n");
      out.write("  		<span><img src=\"images/visiomed_logo.png\" style=\"width:75px;\"></span><br>\r\n");
      out.write("  			<p class=\"copyright\" style=\"margin:0 0 0 0;\">copyrightⓒ 2024 All rights reserved by Team.VisioMed</p>\r\n");
      out.write("		</div>\r\n");
      out.write("  	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<!-- Scripts -->\n");
      out.write("	<script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/jquery.scrollex.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/browser.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/breakpoints.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/util.js\"></script>\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\n");
      out.write("	<script src=\"assets/js/bootstrap.js\"></script>\n");
      out.write("	<script src=\"assets/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("	<!-- awesome font -->\n");
      out.write("	<script src=\"https://kit.fontawesome.com/8b21a455c5.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
