/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-07-24 11:31:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.UserDTO;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Model.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>VisioMed</title>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("@font-face {\n");
      out.write("    font-family: 'Poppins', sans-serif;\n");
      out.write("    font-weight: normal;\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("body {\n");
      out.write("    font-family: 'Poppins', sans-serif;\n");
      out.write("    background-image: url('images/bgimg_1.jpg');\n");
      out.write("    background-size: 100% 80%;\n");
      out.write("    padding-bottom: 100px;\n");
      out.write("    background-repeat: no-repeat;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"landing is-preload\" style=\"padding:0px\">\n");
      out.write("\n");
      out.write("	");

		request.setCharacterEncoding("utf-8");

		String check = request.getParameter("check");
		String status = request.getParameter("status");

		String mo_title = "";
		String mo_content = "";

		UserDTO udto = (UserDTO)session.getAttribute("udto");
	
      out.write("\n");
      out.write("\n");
      out.write("	<div id=\"page-wrapper\">\n");
      out.write("		<!-- Header -->\n");
      out.write("		<header id=\"header\" class=\"alt\">\n");
      out.write("			<h1 style=\"color: black;font-size:xx-large;top:30px;\">\n");
      out.write("				<a href=\"Index.jsp\" style=\"color: black;font-size:55px;\">VisioMed&nbsp;&nbsp;</a>\n");
      out.write("			</h1>\n");
      out.write("			\n");
      out.write("			<nav id=\"nav\" style=\"text-align:right;\">\n");
      out.write("				<i class=\"fa-regular fa-envelope fa-2x\" style=\"color:black;margin-top:20px;\"></i> \n");
      out.write("				<i class=\"fa-solid fa-heart fa-2x\" style=\"color:red;margin-left:20px;\"></i> \n");
      out.write("				<i class=\"fa-regular fa-pen-to-square fa-2x\" style=\"color:black;margin-left:20px;\"></i> \n");
      out.write("				<i class=\"fa-solid fa-user fa-2x\" style=\"color:gray;margin-left:20px;\"></i>\n");
      out.write("				\n");
      out.write("				");
 if (udto != null) { 
      out.write("\n");
      out.write("					<sup style=\"color:green;font-weight:500;font-size:larger; vertical-align:sub;\">\n");
      out.write("						&nbsp;&nbsp;");
      out.print( udto.getUser_name() );
      out.write("님 로그인\n");
      out.write("					</sup>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("				\n");
      out.write("				<ul>\n");
      out.write("					<li><a href=\"Index.jsp\" style=\"color:#696969;font-size:xx-large;\">홈</a></li>\n");
      out.write("					<li><a href=\"select_handi.jsp\" style=\"color:#696969;font-size:xx-large;\">정보 등록 및 조회&nbsp;&nbsp;&nbsp;<i class='icon solid fa fa-angle-down'></i></a>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"reg_handi.jsp\">회원 정보 등록</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					<li class='sub-menu'><a href=\"#\" style=\"color:#696969;font-size:xx-large;\">커뮤니티&nbsp;&nbsp;&nbsp;<i class='fa fa-angle-down'></i></a>\n");
      out.write("						<ul>\n");
      out.write("							<li><a href=\"qnaMain.jsp\">문의하기</a></li>\n");
      out.write("							<li><a href=\"storyMain.jsp\">정보 공유</a></li>\n");
      out.write("						</ul>\n");
      out.write("					</li>\n");
      out.write("					<li class='sub-menu'><a href=\"Mypage.jsp\" style=\"color:#696969;font-size:xx-large;\">마이페이지</a></li>\n");
      out.write("\n");
      out.write("					");
 if (udto != null) { 
      out.write("\n");
      out.write("						<li><a href=\"LogoutServiceCon.do\" class=\"button\" style=\"color: black;font-size:xx-large;\">로그아웃</a></li>\n");
      out.write("					");
 } else { 
      out.write("\n");
      out.write("						<li><a href=\"Login.jsp\" class=\"button\" style=\"color:#816259;font-size:xx-large;\">로그인</a></li>\n");
      out.write("					");
 } 
      out.write("\n");
      out.write("				</ul>\n");
      out.write("			</nav>\n");
      out.write("		</header>\n");
      out.write("		\n");
      out.write("		<!-- Banner -->\n");
      out.write("		<section id=\"banner\">\n");
      out.write("			<!-- CTA -->	\n");
      out.write("			<section id=\"cta\" style=\"height: 500px;\">\n");
      out.write("				");
 if (udto != null) { 
      out.write("\n");
      out.write("					<h3 class=\"big-font\" style=\"color:white;display:inline;\">\n");
      out.write("						");
      out.print( udto.getUser_name() );
      out.write("님, VisioMed 홈페이지에 들어온 것을 환영합니다!<br>\n");
      out.write("						제품 사용 방법을 알고 싶으면 아래 제품 설명 및 사용 방법 버튼을 눌러주세요.\n");
      out.write("					</h3>\n");
      out.write("					<br><br>\n");
      out.write("					<a href=\"Explain.jsp\" class=\"button\" style=\"color:#671909;border-radius:50px;font-size: xx-large;margin-top:70px\">제품 설명 및 사용 방법</a>\n");
      out.write("				");
 } else { 
      out.write("\n");
      out.write("					<h2 style=\"color:white;\">사용하기 쉬운 VisioMed로 안전하게 약을 복용하세요</h2>\n");
      out.write("					<p style=\"color:white;font-size:xx-large;\">\n");
      out.write("						버튼만 누르면 먹을 약을 알려주고 섭취까지 확인하는<br>스마트한 약 보관함\n");
      out.write("					</p>\n");
      out.write("					<a href=\"Join.jsp\" class=\"button\" style=\"min-width:7em;border-radius:50px;font-size: xx-large;color: #671909;\">회원가입</a>\n");
      out.write("					<a href=\"Explain.jsp\" class=\"button\" style=\"color:#671909;border-radius:50px;font-size: xx-large;\">제품 설명 및 사용 방법</a>\n");
      out.write("				");
 } 
      out.write("\n");
      out.write("			</section>\n");
      out.write("		</section>\n");
      out.write("\n");
      out.write("		<!-- Modal -->\n");
      out.write("		<div id=\"modal\" class=\"modal-overlay\">\n");
      out.write("			");

				if (status == null) {
					// 상황별 모달 출력문
				} else if (check.equals("1") && status.equals("1")) {
					mo_title = "가입 성공";
					mo_content = "가입을 환영합니다";
				} else if (check.equals("1") && status.equals("2")) {
					mo_title = "가입 실패";
					mo_content = "양식을 다시 한번 확인해주세요";
				} else if (check.equals("1") && status.equals("3")) {
					mo_title = "3 성공";
					mo_content = "3 환영합니다";
				}
			
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"modal-window\">\n");
      out.write("				<div class=\"title\">\n");
      out.write("					<h2>");
      out.print( mo_title );
      out.write("</h2>\n");
      out.write("				</div>\n");
      out.write("				<div class=\"close-area\">X</div>\n");
      out.write("				<div class=\"content\">\n");
      out.write("					<p>");
      out.print( mo_content );
      out.write("</p>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- Modal Logic -->\n");
      out.write("		<script>\n");
      out.write("			const modal = document.getElementById(\"modal\");\n");
      out.write("			function modalOn() {\n");
      out.write("			    modal.style.display = \"flex\";\n");
      out.write("			}\n");
      out.write("			function isModalOn() {\n");
      out.write("			    return modal.style.display === \"flex\";\n");
      out.write("			}\n");
      out.write("			function modalOff() {\n");
      out.write("			    modal.style.display = \"none\";\n");
      out.write("			}\n");
      out.write("			const closeBtn = modal.querySelector(\".close-area\");\n");
      out.write("			closeBtn.addEventListener(\"click\", e => {\n");
      out.write("			    modalOff();\n");
      out.write("			});\n");
      out.write("			modal.addEventListener(\"click\", e => {\n");
      out.write("			    const evTarget = e.target;\n");
      out.write("			    if (evTarget.classList.contains(\"modal-overlay\")) {\n");
      out.write("			        modalOff();\n");
      out.write("			    }\n");
      out.write("			});\n");
      out.write("			window.addEventListener(\"keyup\", e => {\n");
      out.write("			    if (isModalOn() && e.key === \"Escape\") {\n");
      out.write("			        modalOff();\n");
      out.write("			    }\n");
      out.write("			});\n");
      out.write("			window.onload = function () {\n");
      out.write("			    let qr_check = \"1\";\n");
      out.write("			    if (qr_check == ");
      out.print( check );
      out.write(") {\n");
      out.write("			        modalOn();\n");
      out.write("			    }\n");
      out.write("			};\n");
      out.write("		</script>\n");
      out.write("\n");
      out.write("		<!-- Footer -->\n");
      out.write("		<footer id=\"footer\" style=\"padding:3em 0 3em 0;\">\n");
      out.write("			<div class=\"inner\">\n");
      out.write("				<a href=\"#\" class=\"page-top\" style=\"position: relative;left:350px;\">위로가기</a>\n");
      out.write("				<p style=\"margin:0 0 0 0;\">전화: (+82)010-2512-5397</p>\n");
      out.write("				<p style=\"margin:0 0 0 0;\">주소: 서울시, 성북구, 성북로 176</p>\n");
      out.write("				<span><img src=\"images/visiomed_logo.png\" style=\"width:75px;\"></span><br>\n");
      out.write("				<p class=\"copyright\" style=\"margin:0 0 0 0;\">copyrightⓒ 2024 All rights reserved by Team.VisioMed</p>\n");
      out.write("			</div>\n");
      out.write("		</footer>\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- Scripts -->\n");
      out.write("	<script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/jquery.scrollex.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/browser.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/breakpoints.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/util.js\"></script>\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\n");
      out.write("	<script src=\"assets/js/bootstrap.js\"></script>\n");
      out.write("	<script src=\"assets/js/bootstrap.min.js\"></script>\n");
      out.write("	<script src=\"https://kit.fontawesome.com/8b21a455c5.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
