/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-07-24 11:10:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.UserDTO;
import Model.UserDTO;
import Model.UserDTO;

public final class Join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./header.jsp", Long.valueOf(1721456487285L));
    _jspx_dependants.put("/./footer.jsp", Long.valueOf(1721487489457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Model.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>회원 가입</title>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("   content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("@font-face {\n");
      out.write("    /*font-family: 'GangwonEdu_OTFBoldA';\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/GangwonEdu_OTFBoldA.woff') format('woff');*/\n");
      out.write("    font-family: 'Poppins', sans-serif;\n");
      out.write("    font-weight: normal;\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"is-preload\" style=\"font-family: 'GangwonEdu_OTFBoldA';\">\n");
      out.write("\n");
      out.write("  \n");
      out.write("   <div id=\"page-wrapper\">\n");
      out.write("\n");
      out.write("      <!-- Header -->\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		UserDTO udto = (UserDTO)session.getAttribute("udto");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("		<header id=\"header\">\r\n");
      out.write("			<h1 style=\"color:white;font-size:xx-large;top:10px;\">\r\n");
      out.write("				<a href=\"Index.jsp\" style=\"color:white;font-size:50px;\">VisioMed&nbsp;&nbsp;</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			<nav id=\"nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"Index.jsp\">홈</a></li>\r\n");
      out.write("					<li><a href=\"select_handi.jsp\">정보 등록 및 조회&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='icon solid fa fa-angle-down'></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"reg_handi.jsp\">회원 정보 등록</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"#\">커뮤니티&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='fa fa-angle-down'></i></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"qnaMain.jsp\">문의하기</a></li>\r\n");
      out.write("							<li><a href=\"storyMain.jsp\">정보 공유</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"Mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("\r\n");
      out.write("					");
 if(udto != null){ 
      out.write("\r\n");
      out.write("						<li><a href=\"LogoutServiceCon.do\" class=\"button\" style=\"color: black;\">로그아웃</a></li>\r\n");
      out.write("					");
} else{
      out.write("\r\n");
      out.write("						<li><a href=\"Login.jsp\" class=\"button\" >로그인</a></li>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("      <!-- Main -->\n");
      out.write("      <section id=\"main\" class=\"container\">\n");
      out.write("         <header>\n");
      out.write("            <h2>회원가입</h2>\n");
      out.write("            <p>반갑습니다, VisioMed입니다.</p>\n");
      out.write("         </header>\n");
      out.write("         <div class=\"box\">\n");
      out.write("           \n");
      out.write("            <!-- 사용자와의 관계 : 복지사는 0 보호자는 1 -->\n");
      out.write("            <form action=\"JoinServiceCon.do\" method=\"post\">\n");
      out.write("               <table>\n");
      out.write("                  <thead>\n");
      out.write("                     <h3>가입하기</h3>\n");
      out.write("                  </thead>\n");
      out.write("\n");
      out.write("                  <tbody>\n");
      out.write("                     <tr>\n");
      out.write("						<td>아이디</td>\n");
      out.write("						<td><input id=\"\" type=\"text\" name=\"user_id\"\n");
      out.write("							placeholder=\"아이디를 입력해 주세요.\"> \n");
      out.write("							<span class=\"button small\" onclick=\"idCheck()\">중복확인 \n");
      out.write("							</span>\n");
      out.write("							<!-- 중복 체크 메세지 출력 -->\n");
      out.write("							<span id=\"idcheck\" style=\"color: red;\"></span>\n");
      out.write("					</tr>\n");
      out.write("                     <tr>\n");
      out.write("                        <td>비밀번호</td>\n");
      out.write("                        <td><input type=\"password\" id=\"pwd1\" name=\"user_pw\"\n");
      out.write("                           placeholder=\"5자리 이상 입력해 주세요.\"></td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr>\n");
      out.write("                        <td>비밀번호 확인</td>\n");
      out.write("                        <td><input type=\"password\" id=\"pwd2\" name=\"user_pw\"\n");
      out.write("                           placeholder=\"다시 한 번 입력해 주세요.\"></td>\n");
      out.write("                     </tr>\n");
      out.write("\n");
      out.write("					<!-- 비번 일치 여부 메세지 출력 -->\n");
      out.write("                     <tr>\n");
      out.write("                        <td></td>\n");
      out.write("                        <td>\n");
      out.write("                           <div class=\"alert alert-success\" id=\"alert-success\">비밀번호가\n");
      out.write("                              일치합니다.</div>\n");
      out.write("                           <div class=\"alert alert-danger\" id=\"alert-danger\" style=\"color:red;\">비밀번호가\n");
      out.write("                              일치하지 않습니다.</div>\n");
      out.write("                        </td>\n");
      out.write("                     </tr>\n");
      out.write("\n");
      out.write("                     <tr>\n");
      out.write("                        <td>사용자와의 관계</td>\n");
      out.write("                        <td>\n");
      out.write("                           <div class=\"col-4 col-12-narrower\">\n");
      out.write("                              <input type=\"radio\" id=\"type0\" name=\"user_type\" value=\"0\"\n");
      out.write("                                 checked> <label for=\"type0\" onclick=\"push0()\">복지사(기관)</label>\n");
      out.write("\n");
      out.write("                              <input type=\"radio\" id=\"type1\" name=\"user_type\" value=\"1\">\n");
      out.write("                              <label for=\"type1\" onclick=\"push1()\">보호자(가족)</label>\n");
      out.write("                           </div>\n");
      out.write("                        </td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                     <!-- 복지사일 경우 -->\n");
      out.write("                     <tr class=\"comp\">\n");
      out.write("                        <td>복지관명</td>\n");
      out.write("                        <td><input type=\"text\" name=\"user_company\"\n");
      out.write("                           placeholder=\"회사명을 입력해 주세요.\"></td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr class=\"comp\">\n");
      out.write("                        <td>복지관 전화번호</td>\n");
      out.write("                        <td><input type=\"text\" name=\"user_comtel\"\n");
      out.write("                           placeholder=\"회사 전화번호를 입력해 주세요.\"></td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr class=\"comp\">\n");
      out.write("                        <td>복지사 면허번호</td>\n");
      out.write("                        <td><input type=\"text\" name=\"user_license\"\n");
      out.write("                           placeholder=\"면허번호를 입력해 주세요.\"></td>\n");
      out.write("                     </tr>\n");
      out.write("\n");
      out.write("                     <!-- ------------------------------------------------------ -->\n");
      out.write("                     <tr>\n");
      out.write("                        <td>이름</td>\n");
      out.write("                        <td><input type=\"text\" name=\"user_name\"\n");
      out.write("                           placeholder=\"이름을 입력해 주세요.\"></td>\n");
      out.write("                     <tr>\n");
      out.write("                        <td>생년월일</td>\n");
      out.write("                        <td><input type=\"date\" name=\"user_birthdate\"></td>\n");
      out.write("                     <tr>\n");
      out.write("                        <td>연락처</td>\n");
      out.write("                        <td><input type=\"text\" name=\"user_phone\"\n");
      out.write("                           placeholder=\"숫자만 입력해 주세요.\"></td>\n");
      out.write("                     <tr>\n");
      out.write("                        <td>성별</td>\n");
      out.write("                        <td>\n");
      out.write("                           <div class=\"col-4 col-12-narrower\">\n");
      out.write("                              <input type=\"radio\" id=\"user_gender0\" name=\"user_gender\"\n");
      out.write("                                 value=\"male\" checked> <label for=\"user_gender0\">남자</label>\n");
      out.write("                              <input type=\"radio\" id=\"user_gender1\" name=\"user_gender\"\n");
      out.write("                                 value=\"female\"> <label for=\"user_gender1\">여자</label>\n");
      out.write("                              <input type=\"radio\" id=\"user_gender2\" name=\"user_gender\"\n");
      out.write("                                 value=\"none\"> <label for=\"user_gender2\">선택안함</label>\n");
      out.write("                           </div>\n");
      out.write("                        </td>\n");
      out.write("\n");
      out.write("                     </tr>\n");
      out.write("                     <tr>\n");
      out.write("                        <td>주소</td>\n");
      out.write("                        <td><input type=\"text\" id=\"re_postcode\" name=\"re_postcode\"\n");
      out.write("                           placeholder=\"우편번호\"> <input type=\"button\"\n");
      out.write("                           onclick=\"user_region()\" value=\"우편번호 찾기\"><br> <input\n");
      out.write("                           type=\"text\" id=\"re_roadAddress\" name=\"re_roadAddress\"\n");
      out.write("                           placeholder=\"도로명주소\"> \n");
      out.write("                           <!-- <input type=\"hidden\" id=\"re_jibunAddress\" name=\"re_jibunAddress\"  placeholder=\"지번주소\">     -->\n");
      out.write("                           <span id=\"guide\" style=\"color: #999; display: none\"></span> <input\n");
      out.write("                           type=\"text\" id=\"re_detailAddress\" name=\"re_detailAddress\"\n");
      out.write("                           placeholder=\"상세주소\"> <input type=\"hidden\"\n");
      out.write("                           id=\"re_extraAddress\" name=\"re_extraAddress\" placeholder=\"법정동\">\n");
      out.write("                        </td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr>\n");
      out.write("                        <td align=\"center\" colspan=\"2\"><input type=\"reset\"\n");
      out.write("                           class=\"button alt\" value=\"재입력\"> <input type=\"submit\"\n");
      out.write("                           id=\"submit\" value=\"가입하기\"></td>\n");
      out.write("                     </tr>\n");
      out.write("                     <tr>\n");
      out.write("                     </tr>\n");
      out.write("\n");
      out.write("                  </tbody>\n");
      out.write("               </table>\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <!-- Scripts -->\n");
      out.write("            \n");
      out.write("            <!-- 아이디 중복체크 버튼 클릭했을때 -->\n");
      out.write("			<script type=\"text/javascript\">\n");
      out.write("				function idCheck() {\n");
      out.write("					// 1. 입력한 id 가져오기\n");
      out.write("					let user_id = $('input[name=user_id]').val();\n");
      out.write("					console.log(user_id);\n");
      out.write("\n");
      out.write("					// 2. ajax로 id 보내기(IdCheckServiceCon)\n");
      out.write("					$.ajax({\n");
      out.write("						url : 'IdCheckServiceCon.do', /* 어디로 보낼지*/\n");
      out.write("						type : 'post',\n");
      out.write("						data : { /* 입력한 id data보내기 */\n");
      out.write("							user_id : user_id\n");
      out.write("						},\n");
      out.write("						dataType : \"text\", /* 중복체크 결과값 text로 받아오기 */\n");
      out.write("						success : function(result) {\n");
      out.write("							//alert('성공');\n");
      out.write("							if (result == 'false') {\n");
      out.write("								// 중복 X\n");
      out.write("								$('#idcheck').html('중복되는 아이디가 없습니다.');\n");
      out.write("							} else {\n");
      out.write("								// 중복 O\n");
      out.write("								$('#idcheck').html('이미 사용중인 아이디입니다.');\n");
      out.write("							}\n");
      out.write("						},\n");
      out.write("						error : function() {\n");
      out.write("							alert('실패');\n");
      out.write("						}\n");
      out.write("\n");
      out.write("					});\n");
      out.write("				};\n");
      out.write("				</script>\n");
      out.write("				\n");
      out.write("				<!-- 복지사, 보호자 토글 기능 -->\n");
      out.write("				<script type=\"text/javascript\">\n");
      out.write("					function push0() {\n");
      out.write("						$('.comp').show();\n");
      out.write("					}\n");
      out.write("					function push1() {\n");
      out.write("						$('.comp').hide();\n");
      out.write("					}\n");
      out.write("				</script>\n");
      out.write("     \n");
      out.write("     \n");
      out.write("    		<!-- 주소 관련 scripts -->\n");
      out.write("     		<script>\n");
      out.write("    			// 본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, \n");
      out.write("    			// 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\n");
      out.write("                function user_region() {\n");
      out.write("                       new daum.Postcode({\n");
      out.write("                           oncomplete: function(data) {\n");
      out.write("                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\n");
      out.write("\n");
      out.write("                // 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\n");
      out.write("                let roadAddr = data.roadAddress; // 도로명 주소 변수\n");
      out.write("                let extraRoadAddr = ''; // 참고 항목 변수\n");
      out.write("\n");
      out.write("                // 법정동명이 있을 경우 추가한다. (법정리는 제외)\n");
      out.write("                // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\n");
      out.write("                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\n");
      out.write("                    extraRoadAddr += data.bname;\n");
      out.write("                }\n");
      out.write("                // 건물명이 있고, 공동주택일 경우 추가한다.\n");
      out.write("                if(data.buildingName !== '' && data.apartment === 'Y'){\n");
      out.write("                   extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\n");
      out.write("                }\n");
      out.write("                // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\n");
      out.write("                if(extraRoadAddr !== ''){\n");
      out.write("                    extraRoadAddr = ' (' + extraRoadAddr + ')';\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\n");
      out.write("                document.getElementById('re_postcode').value = data.zonecode;\n");
      out.write("                document.getElementById(\"re_roadAddress\").value = roadAddr;\n");
      out.write("                /* document.getElementById(\"re_jibunAddress\").value = data.jibunAddress; */\n");
      out.write("                \n");
      out.write("                // 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\n");
      out.write("                if(roadAddr !== ''){\n");
      out.write("                    document.getElementById(\"re_extraAddress\").value = extraRoadAddr;\n");
      out.write("                } else {\n");
      out.write("                    document.getElementById(\"re_extraAddress\").value = '';\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                let guideTextBox = document.getElementById(\"guide\");\n");
      out.write("                // 사용자가 '선택 안함'을 클릭한 경우, 예상 주소라는 표시를 해준다.\n");
      out.write("                if(data.autoRoadAddress) {\n");
      out.write("                    let expRoadAddr = data.autoRoadAddress + extraRoadAddr;\n");
      out.write("                    guideTextBox.innerHTML = '(예상 도로명 주소 : ' + expRoadAddr + ')';\n");
      out.write("                    guideTextBox.style.display = 'block';\n");
      out.write("\n");
      out.write("                } else if(data.autoJibunAddress) {\n");
      out.write("                    let expJibunAddr = data.autoJibunAddress;\n");
      out.write("                    guideTextBox.innerHTML = '(예상 지번 주소 : ' + expJibunAddr + ')';\n");
      out.write("                    guideTextBox.style.display = 'block';\n");
      out.write("                } else {\n");
      out.write("                    guideTextBox.innerHTML = '';\n");
      out.write("                    guideTextBox.style.display = 'none';\n");
      out.write("                }\n");
      out.write("            	}\n");
      out.write("        		}).open();\n");
      out.write("   			 }\n");
      out.write("			</script>\n");
      out.write("\n");
      out.write("            <script>\n");
      out.write("            // 카카오 주소 api\n");
      out.write("            function findAddr(){ new daum.Postcode({ oncomplete: function(data)\n");
      out.write("            { console.log(data); // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분. \n");
      out.write("            // 도로명 주소의 노출 규칙에 따라 주소를 표시한다. // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여\n");
      out.write("            분기 한다. let roadAddr = data.roadAddress; \n");
      out.write("            // 도로명 주소 변수 let jibunAddr =\n");
      out.write("            data.jibunAddress; \n");
      out.write("            // 지번 주소 변수 \n");
      out.write("            // 우편번호와 주소 정보를 해당 필드에 넣는다.\n");
      out.write("            document.getElementById('member_post').value = data.zonecode;\n");
      out.write("            if(roadAddr !== ''){ document.getElementById(\"member_addr\").value =\n");
      out.write("            roadAddr; } else if(jibunAddr !== ''){\n");
      out.write("            document.getElementById(\"member_addr\").value = jibunAddr; } }\n");
      out.write("            }).open(); }\n");
      out.write("            </script>\n");
      out.write("            <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("\n");
      out.write("		  </div>    \n");
      out.write("\n");
      out.write("            <!-- 비밀번호 일치 로직 + 불일치 시 전달 막기  제어 -->\n");
      out.write("            <script type=\"text/javascript\">\n");
      out.write("		      $(function() {\n");
      out.write("		         $(\"#alert-success\").hide();\n");
      out.write("		         $(\"#alert-danger\").hide();\n");
      out.write("		         $(\"input\").keyup(function() {\n");
      out.write("		            let pwd1 = $(\"#pwd1\").val();\n");
      out.write("		            let pwd2 = $(\"#pwd2\").val();\n");
      out.write("		            if (pwd1 != \"\" || pwd2 != \"\") {\n");
      out.write("		               if (pwd1 == pwd2) {\n");
      out.write("		                  $(\"#alert-success\").show();\n");
      out.write("		                  $(\"#alert-danger\").hide();\n");
      out.write("		                  $(\"#submit\").removeAttr(\"disabled\");\n");
      out.write("		               } else {\n");
      out.write("		                  $(\"#alert-success\").hide();\n");
      out.write("		                  $(\"#alert-danger\").show();\n");
      out.write("		                  $(\"#submit\").attr(\"disabled\", \"disabled\");\n");
      out.write("		               }\n");
      out.write("		            }\n");
      out.write("		         });\n");
      out.write("		      });\n");
      out.write("  			</script>\n");
      out.write("  			\n");
      out.write("	</section>\n");
      out.write("	</div>\n");
      out.write("	  	\n");
      out.write("\n");
      out.write("			<!-- Footer -->\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer id=\"footer\" style=\"padding:3em 0 3em 0;\">\r\n");
      out.write("  		<div class=\"inner\">\r\n");
      out.write("  		<a href=\"#\" class=\"page-top\" style=\"position: relative;left:350px;\">위로가기</a>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">전화: (+82)010-2512-5397</p>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">주소: 서울시, 성북구, 성북로 176</p>\r\n");
      out.write("  		<span><img src=\"images/visiomed_logo.png\" style=\"width:75px;\"></span><br>\r\n");
      out.write("  			<p class=\"copyright\" style=\"margin:0 0 0 0;\">copyrightⓒ 2024 All rights reserved by Team.VisioMed</p>\r\n");
      out.write("		</div>\r\n");
      out.write("  	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("				\n");
      out.write("\n");
      out.write("\n");
      out.write("			<script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("            <script src=\"assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("            <script src=\"assets/js/jquery.scrollex.min.js\"></script>\n");
      out.write("            <script src=\"assets/js/browser.min.js\"></script>\n");
      out.write("            <script src=\"assets/js/breakpoints.min.js\"></script>\n");
      out.write("            <script src=\"assets/js/util.js\"></script>\n");
      out.write("            <script src=\"assets/js/main.js\"></script>\n");
      out.write("            <script src=\"assets/js/bootstrap.js\"></script>\n");
      out.write("            <script src=\"assets/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <!-- awesome font -->\n");
      out.write("            <script src=\"https://kit.fontawesome.com/8b21a455c5.js\"\n");
      out.write("               crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
