/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-07-24 10:58:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.QnaDAO;
import Model.QnaDTO;
import Model.StoryDTO;
import java.util.ArrayList;
import Model.StoryDAO;
import Model.UserDTO;
import Model.UserDTO;
import Model.UserDTO;

public final class Mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./header.jsp", Long.valueOf(1721456487285L));
    _jspx_dependants.put("/./footer.jsp", Long.valueOf(1721487489457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("Model.StoryDTO");
    _jspx_imports_classes.add("Model.UserDTO");
    _jspx_imports_classes.add("Model.QnaDTO");
    _jspx_imports_classes.add("Model.QnaDAO");
    _jspx_imports_classes.add("Model.StoryDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>마이페이지</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("   content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("tr, th, td {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("@font-face {\r\n");
      out.write("    font-family: 'GangwonEdu_OTFBoldA';\r\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/GangwonEdu_OTFBoldA.woff') format('woff');\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"is-preload\" style=\"font-family: 'GangwonEdu_OTFBoldA';\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Header -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		UserDTO udto = (UserDTO)session.getAttribute("udto");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("		<header id=\"header\">\r\n");
      out.write("			<h1 style=\"color:white;font-size:xx-large;top:10px;\">\r\n");
      out.write("				<a href=\"Index.jsp\" style=\"color:white;font-size:50px;\">VisioMed&nbsp;&nbsp;</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			<nav id=\"nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"Index.jsp\">홈</a></li>\r\n");
      out.write("					<li><a href=\"select_handi.jsp\">정보 등록 및 조회&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='icon solid fa fa-angle-down'></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"reg_handi.jsp\">회원 정보 등록</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"#\">커뮤니티&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='fa fa-angle-down'></i></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"qnaMain.jsp\">문의하기</a></li>\r\n");
      out.write("							<li><a href=\"storyMain.jsp\">정보 공유</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"Mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("\r\n");
      out.write("					");
 if(udto != null){ 
      out.write("\r\n");
      out.write("						<li><a href=\"LogoutServiceCon.do\" class=\"button\" style=\"color: black;\">로그아웃</a></li>\r\n");
      out.write("					");
} else{
      out.write("\r\n");
      out.write("						<li><a href=\"Login.jsp\" class=\"button\" >로그인</a></li>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");

   		// 회원
   		String user_id = udto.getUser_id();
   		
   		// 정보 공유
   		ArrayList<StoryDTO> mystories = new StoryDAO().myBoardAll(user_id);
   		
   		// 문의하기 
   		QnaDTO qdto;
   		
   		// 문의하기 답변
   
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- Main -->\r\n");
      out.write("      <section id=\"main\" class=\"container\" >\r\n");
      out.write("         <header>\r\n");
      out.write("            <h2>마이페이지</h2>\r\n");
      out.write("            <p>내 정보 관리</p>\r\n");
      out.write("         </header>\r\n");
      out.write("         <div class=\"box\">\r\n");
      out.write("        	<div class=\"row-6 row-12-mobilep\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mypage\" style=\"text-align:center;\">\r\n");
      out.write("            <h3><span class=\"big-font\">");
      out.print( udto.getUser_name() );
      out.write("</span>&nbsp;&nbsp;님의 페이지입니다.</h3>\r\n");
      out.write("            \r\n");
      out.write("			<!-- 회원 정보 수정 : 페이지 이동-->\r\n");
      out.write("            <h4><input type=\"button\" style=\"width:fit-content; margin:5px 5px; border-radius:25px !important;\" class=\"button\" value=\"내 정보 수정\" onclick=\"updateInfo()\"></h4>\r\n");
      out.write("            </div><br><br>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 내가 쓴 게시글 보기 -->\r\n");
      out.write("            <h4 style=\"text-align:center;\">내가 쓴 게시글</h4><br>\r\n");
      out.write("           	<table>\r\n");
      out.write("           	<thead>\r\n");
      out.write("           		<tr>\r\n");
      out.write("           			<th style=\"text-align:center\">번호</th>\r\n");
      out.write("           			<th style=\"text-align:center\">게시글 제목</th>\r\n");
      out.write("           			<th style=\"text-align:center\">작성일</th>\r\n");
      out.write("           			<th style=\"text-align:center\"><i class=\"fa-solid fa-eye\"></i></th>\r\n");
      out.write("           			<th style=\"text-align:center\"><i class=\"fa-solid fa-heart\"></i></th>\r\n");
      out.write("           		</tr>\r\n");
      out.write("           	</thead>\r\n");
      out.write("           	\r\n");
      out.write("           	<tbody>\r\n");
      out.write("            ");
 if(!mystories.isEmpty()){  int num=1; 
      out.write("\r\n");
      out.write("            	");
 for (StoryDTO st : mystories){ 
      out.write("\r\n");
      out.write("           		<tr>\r\n");
      out.write("           			<td>");
      out.print( num );
      out.write("</td>\r\n");
      out.write("	           		<td>\r\n");
      out.write("	           			<a href=\"storySelect.jsp?story_seq=");
      out.print( st.getStory_seq() );
      out.write('"');
      out.write('>');
      out.print( st.getStory_title() );
      out.write("</a>\r\n");
      out.write("	           		</td>\r\n");
      out.write("	           		<td>");
      out.print( st.getStory_joindate() );
      out.write("</td>\r\n");
      out.write("	           		<td>");
      out.print( st.getStory_cnt() );
      out.write("</td>\r\n");
      out.write("	           		<td>");
      out.print( st.getStory_like() );
      out.write("</td>\r\n");
      out.write("           		</tr>\r\n");
      out.write("            	");
 num++; } 
      out.write("\r\n");
      out.write("            <!-- 게시글이 없을 경우 -->\r\n");
      out.write("            ");
} else {
      out.write("  \r\n");
      out.write("        		<tr style=\"text-align:center\">\r\n");
      out.write("           			<td colspan=\"5\">게시물이 없습니다.</td>\r\n");
      out.write("           		</tr>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("           	</table>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 답변 달렸을 경우, 업데이트 : ajax -->\r\n");
      out.write("            <br>\r\n");
      out.write("            <h4 style=\"text-align:center;\">내 문의글 답변 확인하기</h4><br>\r\n");
      out.write("            <table>\r\n");
      out.write("            <thead>\r\n");
      out.write("	            <tr>\r\n");
      out.write("	            	<th style=\"text-align:center\">번호</th>\r\n");
      out.write("	            	<th style=\"text-align:center\">문의글 제목</th>\r\n");
      out.write("	            	<th style=\"text-align:center\">작성일</th>\r\n");
      out.write("	            	<th style=\"text-align:center\">답변</th>\r\n");
      out.write("	            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tbody id = \"tbody\">\r\n");
      out.write("	           <!-- 문의글 답변 조회 리스트 -->\r\n");
      out.write("            </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("            	\r\n");
      out.write("\r\n");
      out.write("		</div>	\r\n");
      out.write("   </div>\r\n");
      out.write(" </section>\r\n");
      out.write(" </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- Scripts -->\r\n");
      out.write("   \r\n");
      out.write("	<script>\r\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("		let user_id = \"");
      out.print( user_id );
      out.write("\";\r\n");
      out.write("		console.log(user_id);\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		// 내 문의글 전체 조회 + 답변 여부\r\n");
      out.write("   		$.ajax({\r\n");
      out.write("   			url : \"SelectQnaReplyServiceCon.do\",\r\n");
      out.write("   			type : \"post\",\r\n");
      out.write("   			data : {\r\n");
      out.write("	        	user_id : user_id,\r\n");
      out.write("	        },\r\n");
      out.write("   			dataType : \"json\", \r\n");
      out.write("   			success : function(res){\r\n");
      out.write("   				$('#tbody').html('');\r\n");
      out.write("   				if(res.length == 0){\r\n");
      out.write("	            	table = '<tr><td colspan=\"4\" align=\"center\">내가 작성한 문의글이 없습니다.</td></tr>'\r\n");
      out.write("	            }\r\n");
      out.write("	            else{  \r\n");
      out.write("	            	let table =\"\";\r\n");
      out.write("	            	for (let i = 0; i < res.length; i++) {\r\n");
      out.write("	            		table = '<tr>';\r\n");
      out.write("	            		table += '<td>'+ (i+1) +'</td>';\r\n");
      out.write("	            		let qna_seq = res[i].qna_seq;\r\n");
      out.write("	            		console.log(qna_seq);\r\n");
      out.write("	            		table += '<td><a href=qnaSelect.jsp?qna_seq='+qna_seq+'>'+ res[i].qna_title +'</a></td>';\r\n");
      out.write("						table += '<td>'+ res[i].qna_joindate +'</td>';\r\n");
      out.write("						if(res[i].rep_seq != \"\"){\r\n");
      out.write("							/*\r\n");
      out.write("							if(res[i].qna_seq == res[i].qna_seq){\r\n");
      out.write("								table += '<td><i class=\"fa-solid fa-envelope\"></i>'\r\n");
      out.write("											+'&nbsp;&nbsp;<i class=\"fa-solid fa-plus fa-1x\"></i></td>';\r\n");
      out.write("							} else{ */\r\n");
      out.write("								table += '<td><i class=\"fa-solid fa-envelope\"></i></td>';\r\n");
      out.write("							//}\r\n");
      out.write("							\r\n");
      out.write("						} else {\r\n");
      out.write("							table += '<td></td>'\r\n");
      out.write("						}\r\n");
      out.write("						table += '</tr>';\r\n");
      out.write("						$('#tbody').append(table);\r\n");
      out.write("	            	}\r\n");
      out.write("	            }\r\n");
      out.write("	        },\r\n");
      out.write("	        error : function() {\r\n");
      out.write("	            alert('문의 답변 조회 실패!')\r\n");
      out.write("	        }\r\n");
      out.write("	    })\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("   <!-- 회원 정보 수정 페이지 이동 -->\r\n");
      out.write("   	function updateInfo() {\r\n");
      out.write("   		location.href=\"update_info.jsp?user_id=");
      out.print( udto.getUser_id() );
      out.write("\";\r\n");
      out.write("   	};\r\n");
      out.write("   	\r\n");
      out.write("   	document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("   		let succ = ");
      out.print( request.getParameter("status") );
      out.write("\r\n");
      out.write("   		if(succ == 1){\r\n");
      out.write("   			alert(\"회원 정보가 수정되었습니다.\")\r\n");
      out.write("   		}\r\n");
      out.write("   	});\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Footer -->\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer id=\"footer\" style=\"padding:3em 0 3em 0;\">\r\n");
      out.write("  		<div class=\"inner\">\r\n");
      out.write("  		<a href=\"#\" class=\"page-top\" style=\"position: relative;left:350px;\">위로가기</a>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">전화: (+82)010-2512-5397</p>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">주소: 서울시, 성북구, 성북로 176</p>\r\n");
      out.write("  		<span><img src=\"images/visiomed_logo.png\" style=\"width:75px;\"></span><br>\r\n");
      out.write("  			<p class=\"copyright\" style=\"margin:0 0 0 0;\">copyrightⓒ 2024 All rights reserved by Team.VisioMed</p>\r\n");
      out.write("		</div>\r\n");
      out.write("  	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <script src=\"https://kit.fontawesome.com/8b21a455c5.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("   <script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/util.js\"></script>\r\n");
      out.write("   <script src=\"assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
