/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-07-24 11:11:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.SelectHandiDTO;
import com.google.gson.Gson;
import java.io.PrintWriter;
import Model.UserDTO;
import Model.UserDTO;
import Model.UserDTO;

public final class reg_005fbox_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./header.jsp", Long.valueOf(1721456487285L));
    _jspx_dependants.put("/./footer.jsp", Long.valueOf(1721487489457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("com.google.gson.Gson");
    _jspx_imports_classes.add("Model.UserDTO");
    _jspx_imports_classes.add("Model.SelectHandiDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>약 보관함 등록</title>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@font-face {\r\n");
      out.write("    /*font-family: 'GangwonEdu_OTFBoldA';\r\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/GangwonEdu_OTFBoldA.woff') format('woff');*/\r\n");
      out.write("    font-family: 'Poppins', sans-serif;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("li{\r\n");
      out.write("    list-style:none;\r\n");
      out.write("    padding-left:0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>	\r\n");
      out.write("<body class=\"is-preload\" style=\"font-family: 'GangwonEdu_OTFBoldA';\">\r\n");
      out.write("	<div id=\"page-wrapper\">\r\n");
      out.write("		");
 
			request.setCharacterEncoding("UTF-8");
			
			String seq = request.getParameter("seq");
			String name = request.getParameter("name");
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Header -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		UserDTO udto = (UserDTO)session.getAttribute("udto");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("		<header id=\"header\">\r\n");
      out.write("			<h1 style=\"color:white;font-size:xx-large;top:10px;\">\r\n");
      out.write("				<a href=\"Index.jsp\" style=\"color:white;font-size:50px;\">VisioMed&nbsp;&nbsp;</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			<nav id=\"nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"Index.jsp\">홈</a></li>\r\n");
      out.write("					<li><a href=\"select_handi.jsp\">정보 등록 및 조회&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='icon solid fa fa-angle-down'></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"reg_handi.jsp\">회원 정보 등록</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"#\">커뮤니티&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='fa fa-angle-down'></i></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"qnaMain.jsp\">문의하기</a></li>\r\n");
      out.write("							<li><a href=\"storyMain.jsp\">정보 공유</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"Mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("\r\n");
      out.write("					");
 if(udto != null){ 
      out.write("\r\n");
      out.write("						<li><a href=\"LogoutServiceCon.do\" class=\"button\" style=\"color: black;\">로그아웃</a></li>\r\n");
      out.write("					");
} else{
      out.write("\r\n");
      out.write("						<li><a href=\"Login.jsp\" class=\"button\" >로그인</a></li>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Main -->\r\n");
      out.write("		<section id=\"main\" class=\"container\" style=\"text-align: center; \">\r\n");
      out.write("			<header>\r\n");
      out.write("				<h2>약 보관함 등록</h2>\r\n");
      out.write("				<hr>\r\n");
      out.write("				<h4>\r\n");
      out.write("				<i class=\"fa-solid fa-capsules\"></i>\r\n");
      out.write("					<!-- 실사용자 이름 출력 (수정 필요)-->\r\n");
      out.write("					<strong>");
      out.print(name );
      out.write("</strong>님의 약 보관함 페이지입니다. 여기서 약 정보를 등록, 수정, 그리고 삭제할 수 있습니다.\r\n");
      out.write("				</h4>\r\n");
      out.write("				<span></span>\r\n");
      out.write("			</header>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("				<div>\r\n");
      out.write("					<div class=\"row-6 row-12-mobilep\">\r\n");
      out.write("						<table style=\"\">\r\n");
      out.write("							<thead>\r\n");
      out.write("			                     <tr>\r\n");
      out.write("			                        <td colspan=\"7vw\" align=\"center\">\r\n");
      out.write("			                        <i class=\"fa-solid fa-check\"></i> &nbsp;&nbsp;함에 맞는 사용자의 약 이름를 등록해 주세요 (예: 타이레놀, 후시딘).<br>\r\n");
      out.write("			                        <i class=\"fa-solid fa-check\"></i> &nbsp;&nbsp;처방의료기관(병원명, 약국명)을 입력해 주세요 (예: 서울xx병원).<br>\r\n");
      out.write("			                        <i class=\"fa-solid fa-check\"></i> &nbsp;&nbsp;용법에 약의 사용법이나 사용주기 및 제한 등의 간단한 설명을 입력해 주세요. <br>\r\n");
      out.write("			                        <i class=\"fa-solid fa-check\"></i> &nbsp;&nbsp;약의 처방일자를 선택 후 복용시간 알람을 맞춰 주세요. </td>\r\n");
      out.write("			                     </tr>\r\n");
      out.write("\r\n");
      out.write("			                     <tr id = \"colSize\">\r\n");
      out.write("			                        <td align=\"center\">&nbsp;&nbsp;&nbsp;&nbsp;함&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("			                        <td align=\"center\">약 이름</td> <!-- med_box -->\r\n");
      out.write("			                        <td align=\"center\">처방 의료 기관</td> <!-- med_hosp -->\r\n");
      out.write("			                        <td align=\"center\">용 법</td> <!-- way -->\r\n");
      out.write("			                        <td align=\"center\">처방 일자</td> <!-- med_date -->\r\n");
      out.write("			                        <td align=\"center\">복용시간 알람</td> <!-- med_alarm -->\r\n");
      out.write("			                        <td align=\"center\">개별수정</td> <!-- med_update -->\r\n");
      out.write("			                        <td align=\"center\">개별삭제</td> <!-- med_remove -->\r\n");
      out.write("			                     </tr>\r\n");
      out.write("		                     </thead>\r\n");
      out.write("		                     \r\n");
      out.write("		                     \r\n");
      out.write("		                     <tbody id = \"data_list\">\r\n");
      out.write("			                     <tr>\r\n");
      out.write("			                        <td align=\"center\">1</td>\r\n");
      out.write("			                        <td bgcolor=\"white\"><input type=\"text\" name=\"med_box1\"style=\"width: 170px;\"></td>             \r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_hosp1\" style=\"width: 170px;\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_way1\" style=\"width: 170px;\"></td>   \r\n");
      out.write("			                        <td><input type=\"date\" name=\"med_date1\"></td>    \r\n");
      out.write("			                        <td><input type=\"time\" name=\"med_alarm1\" style=\"margin-left:15px\"></td>  \r\n");
      out.write("			                        <td><input type=\"button\" class=\"button updatebtn\" id=\"med_update1\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                        <td><input type=\"button\" class=\"button\" id=\"med_remove1\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                     </tr>\r\n");
      out.write("			\r\n");
      out.write("			                     <tr>\r\n");
      out.write("			                        <td   align=\"center\">2</td>\r\n");
      out.write("			                        <td bgcolor=\"white\"><input type=\"text\" name=\"med_box2\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_hosp2\" style=\"width: 170px;\"></td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"med_way2\" style=\"width: 170px;\"></td>   \r\n");
      out.write("                                    <td><input type=\"date\" name=\"med_date2\"></td>    \r\n");
      out.write("                                    <td><input type=\"time\" name=\"med_alarm2\" style=\"margin-left:15px\"></td>\r\n");
      out.write("                                    <td><input type=\"button\" class=\"button updatebtn\" id=\"med_update2\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                        <td><input type=\"button\" class=\"button deletebtn\" id=\"med_remove2\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>  \r\n");
      out.write("			                     </tr>\r\n");
      out.write("			\r\n");
      out.write("			                     <tr>\r\n");
      out.write("			                        <td   align=\"center\">3</td>\r\n");
      out.write("			                        <td bgcolor=\"white\"><input type=\"text\" name=\"med_box3\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_hosp3\" style=\"width: 170px;\"></td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"med_way3\" style=\"width: 170px;\"></td>   \r\n");
      out.write("                                    <td><input type=\"date\" name=\"med_date3\"></td>    \r\n");
      out.write("                                    <td><input type=\"time\" name=\"med_alarm3\" style=\"margin-left:15px\"></td> \r\n");
      out.write("                                    <td><input type=\"button\" class=\"button updatebtn\" id=\"med_update3\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                        <td><input type=\"button\" class=\"button deletebtn\" id=\"med_remove3\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                     </tr>\r\n");
      out.write("			\r\n");
      out.write("			                     <tr>\r\n");
      out.write("			                        <td   align=\"center\">4</td>\r\n");
      out.write("			                        <td bgcolor=\"white\"><input type=\"text\" name=\"med_box4\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_hosp4\" style=\"width: 170px;\"></td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"med_way4\" style=\"width: 170px;\"></td>   \r\n");
      out.write("                                    <td><input type=\"date\" name=\"med_date4\"></td>    \r\n");
      out.write("                                    <td><input type=\"time\" name=\"med_alarm4\" style=\"margin-left:15px\"></td>\r\n");
      out.write("                                    <td><input type=\"button\" class=\"button updatebtn\" id=\"med_update4\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                        <td><input type=\"button\" class=\"button deletebtn\" id=\"med_remove4\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>    \r\n");
      out.write("			                     </tr>\r\n");
      out.write("			\r\n");
      out.write("			                     <tr>\r\n");
      out.write("			                        <td   align=\"center\">5</td>\r\n");
      out.write("			                        <td bgcolor=\"white\"><input type=\"text\" name=\"med_box5\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_hosp5\" style=\"width: 170px;\"></td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"med_way5\" style=\"width: 170px;\"></td>   \r\n");
      out.write("                                    <td><input type=\"date\" name=\"med_date5\"></td>    \r\n");
      out.write("                                    <td><input type=\"time\" name=\"med_alarm5\" style=\"margin-left:15px\"></td>\r\n");
      out.write("									<td><input type=\"button\" class=\"button updatebtn\" id=\"med_update5\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                        <td><input type=\"button\" class=\"button deletebtn\" id=\"med_remove5\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>     \r\n");
      out.write("			                     </tr>\r\n");
      out.write("			\r\n");
      out.write("			                     <tr>\r\n");
      out.write("			                        <td   align=\"center\">6</td>\r\n");
      out.write("			                        <td bgcolor=\"white\"><input type=\"text\" name=\"med_box6\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_hosp6\" style=\"width: 170px;\"></td>\r\n");
      out.write("                                    <td><input type=\"text\" name=\"med_way6\" style=\"width: 170px;\"></td>   \r\n");
      out.write("                                    <td><input type=\"date\" name=\"med_date6\"></td>    \r\n");
      out.write("                                    <td><input type=\"time\" name=\"med_alarm6\" style=\"margin-left:15px\"></td>\r\n");
      out.write("                                    <td><input type=\"button\" class=\"button updatebtn\" id=\"med_update6\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                        <td><input type=\"button\" class=\"button deletebtn\" id=\"med_remove6\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>      \r\n");
      out.write("			                     </tr>\r\n");
      out.write("			                     \r\n");
      out.write("			                    <tr>\r\n");
      out.write("			                        <td   align=\"center\">7</td>\r\n");
      out.write("			                        <td bgcolor=\"white\"><input type=\"text\" name=\"med_box7\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_hosp7\" style=\"width: 170px;\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_way7\" style=\"width: 170px;\"></td>   \r\n");
      out.write("			                        <td><input type=\"date\" name=\"med_date7\"></td>    \r\n");
      out.write("                                    <td><input type=\"time\" name=\"med_alarm7\" style=\"margin-left:15px\"></td>\r\n");
      out.write("                                    <td><input type=\"button\" class=\"button updatebtn\" id=\"med_update7\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                        <td><input type=\"button\" class=\"button deletebtn\" id=\"med_remove7\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>    \r\n");
      out.write("			                    </tr>\r\n");
      out.write("			                    \r\n");
      out.write("			                    <tr>\r\n");
      out.write("			                        <td   align=\"center\">8</td>\r\n");
      out.write("			                        <td bgcolor=\"white\"><input type=\"text\" name=\"med_box8\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_hosp8\" style=\"width: 170px;\"></td>\r\n");
      out.write("			                        <td><input type=\"text\" name=\"med_way8\" style=\"width: 170px;\"></td>   \r\n");
      out.write("			                        <td><input type=\"date\" name=\"med_date8\"></td>    \r\n");
      out.write("                                    <td><input type=\"time\" name=\"med_alarm8\" style=\"margin-left:15px\"></td>\r\n");
      out.write("                                    <td><input type=\"button\" class=\"button updatebtn\" id=\"med_update8\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>\r\n");
      out.write("			                        <td><input type=\"button\" class=\"button deletebtn\" id=\"med_remove8\" style=\"margin-left:15px; font-family: 'GangwonEdu_OTFBoldA';\" value =\"클릭\"></td>    \r\n");
      out.write("			                    </tr>\r\n");
      out.write("			                    \r\n");
      out.write("			                     <tr>\r\n");
      out.write("			                        <td colspan=\"7\" align=\"center\">\r\n");
      out.write("			                        <input type=\"button\" onclick=\"RegBoxAll()\" value=\"전체 일괄 정보등록\"> \r\n");
      out.write("			                        <input type=\"reset\" onclick=\"DelBoxAll()\" value=\"전체 초기화\" class=\"button alt\">\r\n");
      out.write("			                        </td> \r\n");
      out.write("			                     </tr>\r\n");
      out.write("		                     </tbody>\r\n");
      out.write("							\r\n");
      out.write("						</table>\r\n");
      out.write("			\r\n");
      out.write("			  			<script>\r\n");
      out.write("			  			</script>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("		</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer id=\"footer\" style=\"padding:3em 0 3em 0;\">\r\n");
      out.write("  		<div class=\"inner\">\r\n");
      out.write("  		<a href=\"#\" class=\"page-top\" style=\"position: relative;left:350px;\">위로가기</a>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">전화: (+82)010-2512-5397</p>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">주소: 서울시, 성북구, 성북로 176</p>\r\n");
      out.write("  		<span><img src=\"images/visiomed_logo.png\" style=\"width:75px;\"></span><br>\r\n");
      out.write("  			<p class=\"copyright\" style=\"margin:0 0 0 0;\">copyrightⓒ 2024 All rights reserved by Team.VisioMed</p>\r\n");
      out.write("		</div>\r\n");
      out.write("  	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Scripts -->\r\n");
      out.write("		<script>\r\n");
      out.write("		document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("			$.ajax({\r\n");
      out.write("		        url : 'SelectMediServiceCon.do',\r\n");
      out.write("		        type : 'post',\r\n");
      out.write("		        data : {\r\n");
      out.write("		        	\"h_seq\" : ");
      out.print(seq);
      out.write("\r\n");
      out.write("		        },\r\n");
      out.write("		        dataType: 'json',\r\n");
      out.write("		        success : function(res) {\r\n");
      out.write("		        	if(res.length !== 0){\r\n");
      out.write("		        		$('#data_list').html('');\r\n");
      out.write("			            let table =\"\";\r\n");
      out.write("			            let med_name;\r\n");
      out.write("			            let med_hosp;\r\n");
      out.write("			            let med_way;\r\n");
      out.write("			            for (let i = 0; i < res.length; i++) {\r\n");
      out.write("			            	med_name='';\r\n");
      out.write("				            med_hosp='';\r\n");
      out.write("				            med_way='';\r\n");
      out.write("				            if(res[i].med_name !== undefined)\r\n");
      out.write("				            	med_name = res[i].med_name;\r\n");
      out.write("				            if(res[i].med_hosp !== undefined)\r\n");
      out.write("				            	med_hosp = res[i].med_hosp;\r\n");
      out.write("				            if(res[i].med_name !== undefined)\r\n");
      out.write("				            	med_way = res[i].med_way;\r\n");
      out.write("				            \r\n");
      out.write("							table = '<tr id=\"'+(i+1)+'\">';\r\n");
      out.write("							table +='<td align=\"center\" >'+res[i].med_box+'</td>'\r\n");
      out.write("							table += '<td bgcolor=\"white\"><input type=\"text\" name=\"med_box'+(i+1)+'\"style=\"width: 170px;\" value='+med_name+'></td>';\r\n");
      out.write("							table += '<td><input type=\"text\" name=\"med_hosp'+(i+1)+'\" style=\"width: 170px;\" value=\"'+med_hosp+'\"></td>';\r\n");
      out.write("							table += '<td><input type=\"text\" name=\"med_way'+(i+1)+'\" style=\"width: 170px;\" value=\"'+med_way+'\"></td>';\r\n");
      out.write("							table += '<td><input type=\"date\" name=\"med_date'+(i+1)+'\" value=\"'+res[i].med_date+'\"></td>';\r\n");
      out.write("							table += '<td><input type=\"time\" name=\"med_alarm'+(i+1)+'\" style=\"margin-left:15px\" value=\"'+res[i].med_alarm+'\"></td>';  \r\n");
      out.write("							table += '<td><input type=\"button\" class=\"button updatebtn\" id=\"med_update'+(i+1)+'\" style=\"margin-left:15px; font-family: \"ImcreSoojin\";\" value =\"클릭\"></td>'; \r\n");
      out.write("							table += '<td><input type=\"button\" class=\"button deletebtn\" id=\"med_delete'+(i+1)+'\" style=\"margin-left:15px; font-family: \"ImcreSoojin\";\" value =\"클릭\"></td>';\r\n");
      out.write("							table += '</tr>';\r\n");
      out.write("							$('#data_list').append(table);\r\n");
      out.write("						}\r\n");
      out.write("			            table = '<tr><td colspan=\"7\" align=\"center\">'\r\n");
      out.write("			            table += '<input type=\"button\" onclick=\"RegBoxAll()\" value=\"전체 일괄 정보등록\" style=\"font-family: \"ImcreSoojin\";\">';\r\n");
      out.write("			            table += '<input type=\"reset\" onclick=\"DelBoxAll()\" value=\"전체 초기화\" class=\"button alt\" style=\"font-family: \"ImcreSoojin\";\"></td></tr>';\r\n");
      out.write("			            $('#data_list').append(table);\r\n");
      out.write("		        	}\r\n");
      out.write("		           },\r\n");
      out.write("		        error : function() {\r\n");
      out.write("		            alert('조회실패!')\r\n");
      out.write("		        }\r\n");
      out.write("		    })\r\n");
      out.write("		});\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		<script>	\r\n");
      out.write("		function RegBoxAll(){\r\n");
      out.write("			let putData=[];\r\n");
      out.write("			\r\n");
      out.write("			$(\"#data_list tr\").each(function(i){\r\n");
      out.write("				let td = $(this).children();\r\n");
      out.write("				\r\n");
      out.write("				//if(td.children().eq(0).val()!='' || td.children().eq(1).val() != '') 테스트중\r\n");
      out.write("				putData.push({\r\n");
      out.write("					\"h_seq\"   : ");
      out.print(seq);
      out.write(",\r\n");
      out.write("					\"med_box\"   : td.eq(0).text(),\r\n");
      out.write("					\"med_name\"  : td.children().eq(0).val(),\r\n");
      out.write("					\"med_hosp\"  : td.children().eq(1).val(),\r\n");
      out.write("					\"med_way\"   : td.children().eq(2).val(),\r\n");
      out.write("					\"med_date\"  : td.children().eq(3).val(),\r\n");
      out.write("					\"med_alarm\" : td.children().eq(4).val(),\r\n");
      out.write("					\"user_id\"   : '");
      out.print(udto.getUser_id());
      out.write("'\r\n");
      out.write("				});\r\n");
      out.write("				\r\n");
      out.write("			})\r\n");
      out.write("			putData.pop();  //마지막 배열 값 제거\r\n");
      out.write("			console.log(putData);\r\n");
      out.write("			// ajax는 비동기 통신이기 때문에 페이지끼리(jsp -> jsp)이동을 할 수 없다.\r\n");
      out.write("			// 그래서 값은 전달이 되더라도 에러를 발생시킨다. success부분 실행x\r\n");
      out.write("			$.ajax({\r\n");
      out.write("		        url : 'RegMediboxServiceCon.do',\r\n");
      out.write("		        type : 'post',\r\n");
      out.write("		        dataType:'json',\r\n");
      out.write("		        data : {\r\n");
      out.write("		        	'func' : 'regboxall',\r\n");
      out.write("		        	'json' : JSON.stringify(putData)\r\n");
      out.write("		        },\r\n");
      out.write("		        success : function(res) {\r\n");
      out.write("		        	console.log(res);\r\n");
      out.write("		        	if(res == \"2\")\r\n");
      out.write("		            	alert('전체 정보 등록 성공');\r\n");
      out.write("		        	else if(res == \"1\")\r\n");
      out.write("		        		alert('일부 정보 등록 실패!\\n기존에 등록되어 있는 정보는 \\n\"개별수정\"으로 정보를 변경해주세요! 없는 정보만 새로 생성되었습니다.');\r\n");
      out.write("		        	else\r\n");
      out.write("		        		alert('전체 정보 등록 실패!\\n기존에 전체 등록을 한번 하셨다면\\n전체 초기화 후 새로 일괄 등록하시거나\\n기존에 등록되어 있는 정보만 수정은 \\n\"개별수정\"으로 변경해주세요!');\r\n");
      out.write("		        },\r\n");
      out.write("		        error:function(request,status,error){\r\n");
      out.write("		            alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		}\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		<script>\r\n");
      out.write("		function DelBoxAll(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("		        url : 'RegMediboxServiceCon.do',\r\n");
      out.write("		        type : 'post',\r\n");
      out.write("		        dataType:'json',\r\n");
      out.write("		        data : {\r\n");
      out.write("		        	'func' : 'delboxall',\r\n");
      out.write("		        	\"h_seq\"   : ");
      out.print(seq);
      out.write("\r\n");
      out.write("		        },\r\n");
      out.write("		        success : function(res) {\r\n");
      out.write("		        	console.log(res);\r\n");
      out.write("		        	if(res == \"1\"){\r\n");
      out.write("		        		alert('전체 정보 삭제 성공!');	\r\n");
      out.write("		        	}\r\n");
      out.write("		        	else{\r\n");
      out.write("		        		alert('전체 정보 삭제 실패!\\n기존에 등록되어 있는 정보는 \\n\"개별삭제\"으로 정보를 삭제해주세요!');\r\n");
      out.write("		        	}\r\n");
      out.write("		        		\r\n");
      out.write("		        	location.reload();\r\n");
      out.write("		        },\r\n");
      out.write("		        error:function(request,status,error){\r\n");
      out.write("		            alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		        }\r\n");
      out.write("		        \r\n");
      out.write("		    });\r\n");
      out.write("		}\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("		<script>	\r\n");
      out.write("        // 버튼 클릭시 Row 값 가져오기\r\n");
      out.write("    	$(document).on(\"click\", \".updatebtn\", function(){\r\n");
      out.write("            let putData1 = [];    // 배열 선언\r\n");
      out.write("            let btnUpdate = $(this);\r\n");
      out.write("\r\n");
      out.write("            // checkBtn.parent() : checkBtn의 부모는 <td>이다.\r\n");
      out.write("            // checkBtn.parent().parent() : <td>의 부모이므로 <tr>이다.\r\n");
      out.write("            let tr = btnUpdate.parent().parent();\r\n");
      out.write("            let td = tr.children();\r\n");
      out.write("            \r\n");
      out.write("            console.log(\"클릭한 Row의 모든 데이터 : \"+tr.text());\r\n");
      out.write("            \r\n");
      out.write("            // 반복문을 이용해서 배열에 값을 담아 사용할 수 도 있다.\r\n");
      out.write("            putData1.push({\r\n");
      out.write("				\"h_seq\"   : ");
      out.print(seq);
      out.write(",\r\n");
      out.write("				\"med_box\"   : td.eq(0).text(),\r\n");
      out.write("				\"med_name\"  : td.children().eq(0).val(),\r\n");
      out.write("				\"med_hosp\"  : td.children().eq(1).val(),\r\n");
      out.write("				\"med_way\"   : td.children().eq(2).val(),\r\n");
      out.write("				\"med_date\"  : td.children().eq(3).val(),\r\n");
      out.write("				\"med_alarm\" : td.children().eq(4).val(),\r\n");
      out.write("				\"user_id\"   : '");
      out.print(udto.getUser_id());
      out.write("'\r\n");
      out.write("			});\r\n");
      out.write("            \r\n");
      out.write("            console.log(\"배열에 담긴 값 : \"+putData1);\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("		        url : 'RegMediboxServiceCon.do',\r\n");
      out.write("		        type : 'post',\r\n");
      out.write("		        dataType:'json',\r\n");
      out.write("		        data : {\r\n");
      out.write("		        	'func' : 'regbox',\r\n");
      out.write("		        	'json' : JSON.stringify(putData1)\r\n");
      out.write("		        },\r\n");
      out.write("		        success : function(res) {\r\n");
      out.write("		        	console.log(res);\r\n");
      out.write("		        	if(res == \"1\")\r\n");
      out.write("		            	alert('개별 정보 등록 성공');\r\n");
      out.write("		        	else\r\n");
      out.write("		        		alert('개별 정보 등록 실패');\r\n");
      out.write("		        	\r\n");
      out.write("		        	location.reload();\r\n");
      out.write("		        },\r\n");
      out.write("		        error:function(request,status,error){\r\n");
      out.write("		            alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		        }\r\n");
      out.write("		    }); \r\n");
      out.write("        });\r\n");
      out.write("		</script>\r\n");
      out.write("		\r\n");
      out.write("				<script>	\r\n");
      out.write("        // 버튼 클릭시 Row 값 가져오기\r\n");
      out.write("    	$(document).on(\"click\", \".deletebtn\", function(){\r\n");
      out.write("            let putData2 = [];    // 배열 선언\r\n");
      out.write("            let btnDelete = $(this);\r\n");
      out.write("\r\n");
      out.write("            // checkBtn.parent() : checkBtn의 부모는 <td>이다.\r\n");
      out.write("            // checkBtn.parent().parent() : <td>의 부모이므로 <tr>이다.\r\n");
      out.write("            let tr = btnDelete.parent().parent();\r\n");
      out.write("            let td = tr.children();\r\n");
      out.write("            \r\n");
      out.write("            console.log(\"클릭한 Row의 모든 데이터 : \"+tr.text());\r\n");
      out.write("            \r\n");
      out.write("            // 반복문을 이용해서 배열에 값을 담아 사용할 수 도 있다.\r\n");
      out.write("            putData2.push({\r\n");
      out.write("				\"h_seq\"   : ");
      out.print(seq);
      out.write(",\r\n");
      out.write("				\"med_box\"   : td.eq(0).text(),\r\n");
      out.write("				\"med_name\"  : td.children().eq(0).val(),\r\n");
      out.write("				\"med_hosp\"  : td.children().eq(1).val(),\r\n");
      out.write("				\"med_way\"   : td.children().eq(2).val(),\r\n");
      out.write("				\"med_date\"  : td.children().eq(3).val(),\r\n");
      out.write("				\"med_alarm\" : td.children().eq(4).val(),\r\n");
      out.write("				\"user_id\"   : '");
      out.print(udto.getUser_id());
      out.write("'\r\n");
      out.write("			});\r\n");
      out.write("            \r\n");
      out.write("            console.log(\"배열에 담긴 값 : \"+putData2);\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("		        url : 'RegMediboxServiceCon.do',\r\n");
      out.write("		        type : 'post',\r\n");
      out.write("		        dataType:'json',\r\n");
      out.write("		        data : {\r\n");
      out.write("		        	'func' : 'delbox',\r\n");
      out.write("		        	'json' : JSON.stringify(putData2)\r\n");
      out.write("		        },\r\n");
      out.write("		        success : function(res) {\r\n");
      out.write("		        	console.log(res);\r\n");
      out.write("		        	if(res == \"1\")\r\n");
      out.write("		            	alert('개별 정보 삭제 성공');\r\n");
      out.write("		        	else\r\n");
      out.write("		        		alert('개별 정보 삭제 실패');\r\n");
      out.write("		        	\r\n");
      out.write("		        	location.reload();\r\n");
      out.write("		        	\r\n");
      out.write("		        },\r\n");
      out.write("		        error:function(request,status,error){\r\n");
      out.write("		            alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("            location.ref = \"reg_box.jsp\";\r\n");
      out.write("        });\r\n");
      out.write("		</script>\r\n");
      out.write("		<script src=\"assets/js/jquery.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/jquery.dropotron.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/jquery.scrollex.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/browser.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/util.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/main.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/bootstrap.js\"></script>\r\n");
      out.write("		<script src=\"assets/js/bootstrap.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("		<!-- awesome font -->\r\n");
      out.write("		<script src=\"https://kit.fontawesome.com/8b21a455c5.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
