/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.90
 * Generated at: 2024-07-24 10:39:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.UserDTO;
import Model.UserDTO;
import Model.UserDTO;

public final class select_005fhandi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./header.jsp", Long.valueOf(1721456487285L));
    _jspx_dependants.put("/./footer.jsp", Long.valueOf(1721487489457L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("Model.UserDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>회원 정보 조회</title>\n");
      out.write("<meta charset=\"utf-8\" />\n");
      out.write("<meta name=\"viewport\"\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("@font-face {\n");
      out.write("    font-family: 'GangwonEdu_OTFBoldA';\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2201-2@1.0/GangwonEdu_OTFBoldA.woff') format('woff');\n");
      out.write("    font-weight: normal;\n");
      out.write("    font-style: normal;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body class=\"is-preload\" style=\"font-family: 'GangwonEdu_OTFBoldA';\">\n");
      out.write("	<div id=\"page-wrapper\">\n");
      out.write("\n");
      out.write("		<!-- Header -->\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>header</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		UserDTO udto = (UserDTO)session.getAttribute("udto");
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<!-- Header -->\r\n");
      out.write("		<header id=\"header\">\r\n");
      out.write("			<h1 style=\"color:white;font-size:xx-large;top:10px;\">\r\n");
      out.write("				<a href=\"Index.jsp\" style=\"color:white;font-size:50px;\">VisioMed&nbsp;&nbsp;</a>\r\n");
      out.write("			</h1>\r\n");
      out.write("			<nav id=\"nav\">\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li><a href=\"Index.jsp\">홈</a></li>\r\n");
      out.write("					<li><a href=\"select_handi.jsp\">정보 등록 및 조회&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='icon solid fa fa-angle-down'></i>\r\n");
      out.write("					</a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"reg_handi.jsp\">회원 정보 등록</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"#\">커뮤니티&nbsp;&nbsp;&nbsp;<i\r\n");
      out.write("							class='fa fa-angle-down'></i></a>\r\n");
      out.write("						<ul>\r\n");
      out.write("							<li><a href=\"qnaMain.jsp\">문의하기</a></li>\r\n");
      out.write("							<li><a href=\"storyMain.jsp\">정보 공유</a></li>\r\n");
      out.write("						</ul></li>\r\n");
      out.write("					<li class='sub-menu'><a href=\"Mypage.jsp\">마이페이지</a></li>\r\n");
      out.write("\r\n");
      out.write("					");
 if(udto != null){ 
      out.write("\r\n");
      out.write("						<li><a href=\"LogoutServiceCon.do\" class=\"button\" style=\"color: black;\">로그아웃</a></li>\r\n");
      out.write("					");
} else{
      out.write("\r\n");
      out.write("						<li><a href=\"Login.jsp\" class=\"button\" >로그인</a></li>\r\n");
      out.write("					");
} 
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</header>\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		<!-- Main -->\n");
      out.write("		<section id=\"main\" class=\"container\">\n");
      out.write("			<header>\n");
      out.write("				<h2>회원 정보 조회</h2>\n");
      out.write("				<p>회원 정보 조회 페이지입니다.</p>\n");
      out.write("			</header>\n");
      out.write("			<div class=\"box\">\n");
      out.write("				\n");
      out.write("				");
 if(!udto.getUser_id().isEmpty()){
      out.write("\n");
      out.write("					<input type=\"hidden\" name=\"user_id\" id = \"user_id\" value=\"");
      out.print( udto.getUser_id() );
      out.write("\"/>  <!-- 다른방법물어볼것 -->\n");
      out.write("				");
}
      out.write("\n");
      out.write("				<h3>회원 전체 리스트</h3>\n");
      out.write("				<p></p>\n");
      out.write("				<input type=\"button\" onclick = \"regbox()\" value=\"약 보관함 등록\" class = \"button\"/>\n");
      out.write("				<input type=\"button\" onclick = \"delhandi()\" value=\"회원정보 삭제\" class = \"button\" />\n");
      out.write("				<div class=\"row\">\n");
      out.write("				<table style=\"text-align:center\">\n");
      out.write("					<thead>\n");
      out.write("						<tr>\n");
      out.write("						<td>선 택</td>\n");
      out.write("						<td>순 번(id)</td>\n");
      out.write("						<td>성 명</td>\n");
      out.write("						<td>성 별 </td>\n");
      out.write("						<td>생년월일</td>\n");
      out.write("						<td>주 소</td>\n");
      out.write("						<td>전화번호</td>\n");
      out.write("						");
if(udto.getUser_type()=='0'){ 
      out.write("\n");
      out.write("							<td>복지사 성명</td>\n");
      out.write("							");
} else{
      out.write("\n");
      out.write("								<td>보호자 성명</td>\n");
      out.write("							");
} 
      out.write("\n");
      out.write("						</tr>\n");
      out.write("					</thead>\n");
      out.write(" 					<tbody id = \"tbody\">\n");
      out.write("					</tbody>\n");
      out.write("				</table>	\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</section>\n");
      out.write("\n");
      out.write("		<!-- Footer -->\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<script src=\"assets/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/toggle.css\">\r\n");
      out.write("\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<footer id=\"footer\" style=\"padding:3em 0 3em 0;\">\r\n");
      out.write("  		<div class=\"inner\">\r\n");
      out.write("  		<a href=\"#\" class=\"page-top\" style=\"position: relative;left:350px;\">위로가기</a>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">전화: (+82)010-2512-5397</p>\r\n");
      out.write("  		<p style=\"margin:0 0 0 0;\">주소: 서울시, 성북구, 성북로 176</p>\r\n");
      out.write("  		<span><img src=\"images/visiomed_logo.png\" style=\"width:75px;\"></span><br>\r\n");
      out.write("  			<p class=\"copyright\" style=\"margin:0 0 0 0;\">copyrightⓒ 2024 All rights reserved by Team.VisioMed</p>\r\n");
      out.write("		</div>\r\n");
      out.write("  	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("	<!-- Scripts -->\n");
      out.write("	<script>\n");
      out.write("	document.addEventListener(\"DOMContentLoaded\", function() {\n");
      out.write("		$.ajax({\n");
      out.write("	        url : 'SelectHandiServiceCon.do',\n");
      out.write("	        type : 'post',\n");
      out.write("	        data : {\n");
      out.write("	        	\"user_id\" : $('input[name=user_id]').val()\n");
      out.write("	        },\n");
      out.write("	        dataType: 'json',\n");
      out.write("	        success : function(res) {\n");
      out.write("	            $('#tbody').html('');\n");
      out.write("	            if(res.length == 0){\n");
      out.write("	            	alert('등록된 환자정보가 없습니다.\\n회원정보등록 창으로 이동합니다.');\n");
      out.write("	            	document.location.href=\"reg_handi.jsp\";\n");
      out.write("	            }\n");
      out.write("	            else{\n");
      out.write("	            	let table =\"\";\n");
      out.write("	            	for (let i = 0; i < res.length; i++) {\n");
      out.write("						table = '<tr>';\n");
      out.write("						table +='<td><div style = \"margin-left: 1.3em\"><input type=\"radio\" id=\"'+res[i].h_seq+'\" name=\"rboChk\"><label for=\"'+res[i].h_seq+'\"></label></div></td>'\n");
      out.write("						table += '<td>'+ (i+1) +'('+res[i].h_seq+')</td>';\n");
      out.write("						table += '<td>'+ res[i].h_name +'</td>';\n");
      out.write("						if(res[i].h_gender === \"M\"){\n");
      out.write("							table += '<td>남</td>';\n");
      out.write("						}else{\n");
      out.write("							table += '<td>여</td>';\n");
      out.write("						}\n");
      out.write("						table += '<td>'+ res[i].h_birthdate.slice(0, 10) +'</td>';\n");
      out.write("						table += '<td>'+ res[i].h_addr +'</td>';\n");
      out.write("						table += '<td>'+ res[i].h_phone +'</td>';\n");
      out.write("						table += '<td>'+ res[i].user_id +'</td>';\n");
      out.write("						table += '</tr>';\n");
      out.write("						$('#tbody').append(table);\n");
      out.write("					}\n");
      out.write("	            }\n");
      out.write("	        },\n");
      out.write("	        error : function() {\n");
      out.write("	            alert('조회실패!')\n");
      out.write("	        }\n");
      out.write("	    })\n");
      out.write("	});\n");
      out.write("	</script>\n");
      out.write("	\n");
      out.write("	<script>\n");
      out.write("	//선택된 라디오버튼의 행의 값을 가져온다.\n");
      out.write("	function regbox(){\n");
      out.write("		let rdoCheck = $(\"input[name=rboChk]:checked\");\n");
      out.write("		let rdoId = $(\"input[name=rboChk]:checked\").attr(\"id\");\n");
      out.write("		let name;\n");
      out.write("		\n");
      out.write("		rdoCheck.each(function(i){\n");
      out.write("			let tr = rdoCheck.parent().parent().parent().eq(i);\n");
      out.write("			let td = tr.children();\n");
      out.write("			\n");
      out.write("			name = td.eq(2).text();\n");
      out.write("			\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("		// 단순 페이지 이동만 할거면 쿼리 스트링이용해서 seq값을 보내주면 되죠\n");
      out.write("		if(rdoId != null){\n");
      out.write("			location.href=\"reg_box.jsp?seq=\"+rdoId+\"&name=\"+name;\n");
      out.write("		}\n");
      out.write("		else{\n");
      out.write("			alert('등록되거나 선택된 환자가 없습니다.');\n");
      out.write("		}\n");
      out.write("		// ajax는 비동기 통신이기 때문에 페이지끼리(jsp -> jsp)이동을 할 수 없다.\n");
      out.write("		// 그래서 값은 전달이 되더라도 에러를 발생시킨다. success부분 실행x\n");
      out.write("		/* $.ajax({\n");
      out.write("	        url : 'reg_box.jsp',\n");
      out.write("	        type : 'post',\n");
      out.write("	        dataType:'json',\n");
      out.write("	        data : {\n");
      out.write("	        	'json' : JSON.stringify(putData)\n");
      out.write("	        },\n");
      out.write("	        success : function(res) {\n");
      out.write("	            alert('성공' + res);\n");
      out.write("	            location.href=\"reg_box.jsp\";\n");
      out.write("	        },\n");
      out.write("	        error:function(request,status,error){\n");
      out.write("	            alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);}\n");
      out.write("	    }); */\n");
      out.write("	}\n");
      out.write("	\n");
      out.write("	function delhandi(){\n");
      out.write("		let rdoCheck = $(\"input[name=rboChk]:checked\");\n");
      out.write("		let seq = $(\"input[name=rboChk]:checked\").attr(\"id\");  //rdoid\n");
      out.write("		\n");
      out.write("		// 단순 페이지 이동만 할거면 쿼리 스트링이용해서 seq값을 보내주면 되죠\n");
      out.write("		if(seq != null){\n");
      out.write("			$.ajax({\n");
      out.write("		        url : 'DeleteHandiServiceCon.do',\n");
      out.write("		        type : 'post',\n");
      out.write("		        data : {\n");
      out.write("		        	'h_seq' : seq\n");
      out.write("		        },\n");
      out.write("		        dataType : 'text',\n");
      out.write("		        success : function(res) {\n");
      out.write("		        	if(res == '1'){\n");
      out.write("		        		alert('회원정보 삭제 성공');\n");
      out.write("		        		\n");
      out.write("		        	}else{\n");
      out.write("		        		alert('회원정보 삭제 실패');\n");
      out.write("		        	}\n");
      out.write("		            	\n");
      out.write("		        },\n");
      out.write("		        error:function(request,status,error){\n");
      out.write("		            alert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);}\n");
      out.write("		    });\n");
      out.write("		}\n");
      out.write("		else{\n");
      out.write("			alert('등록되거나 선택된 환자가 없습니다.');\n");
      out.write("		}\n");
      out.write("		document.location.href=\"select_handi.jsp\";\n");
      out.write("	}\n");
      out.write("	</script>\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.0.js\"></script>\n");
      out.write("	<script src=\"assets/js/jquery.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/jquery.dropotron.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/jquery.scrollex.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/browser.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/breakpoints.min.js\"></script>\n");
      out.write("	<script src=\"assets/js/util.js\"></script>\n");
      out.write("	<script src=\"assets/js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
